version: '3.4'

services:
  raw-data-server:
    image: raw-data-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 3000
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      DB_HOST: rds-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: syrfbackend
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      MAPBOX_ID: ${MAPBOX_ID}
      OPEN_GRAPH_BUCKET_NAME: ${OPEN_GRAPH_BUCKET_NAME}
    ports:
      - 3030:3030
      - 9229:9229
    command: ['node', '--inspect=0.0.0.0:9229', 'src/main.js']
