version: '3.4'

services:
  raw-data-server:
    image: raw-data-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      DB_HOST: rds-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: rawdata
      MQ_HOST: rabbit-mq
      MQ_PORT: 61613
      MQ_USER: guest
      MQ_PASSWORD: guest
      MQ_TOPIC: /topic/rawdata.topic
      MQ_TIMEOUT: 2700000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - rds-db
      - rabbit-mq
    command:
      ['./wait-for-it.sh', '-t', '120', 'rds-db:5432', '--', 'npm', 'start']
  rds-db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: sources
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - rds-db:/var/lib/rds
  rabbit-mq:
    image: rabbitmq:3.7-management
    build:
      context: ./rabbit
      dockerfile: ./Dockerfile
    volumes:
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    expose:
      - 5672
      - 15672
      - 61613
volumes:
  rds-db:
