version: '3.4'

services:
  raw-data-server:
    image: raw-data-server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      DB_HOST: rds-db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: rawdata
      MQ_HOST: rabbit-mq
      MQ_PORT: 61613
      MQ_USER: guest
      MQ_PASSWORD: guest
      MQ_TOPIC: /topic/rawdata.topic
      MQ_TIMEOUT: 2700000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - rds-db
      - rabbit-mq
    command:
      ['./wait-for-it.sh', '-t', '120', 'rds-db:3306', '--', 'npm', 'start']
  rds-db:
    image: mysql:5.7
    command: --max_allowed_packet=100M
    restart: always
    environment:
      MYSQL_DATABASE: rawdata
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - rds-db:/var/lib/rds
    command:
      --innodb_lock_wait_timeout=180
  rabbit-mq:
    image: rabbitmq:3.7-management
    build:
      context: ./rabbit
      dockerfile: ./Dockerfile
    volumes:
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    expose:
      - 5672
      - 15672
      - 61613
volumes:
  rds-db:
