version: '3.4'

services:
  raw-data-server:
    image: raw-data-server
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: 3000
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      DB_HOST: rds-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: syrfbackend
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      MAPBOX_ID: ${MAPBOX_ID}
      OPEN_GRAPH_BUCKET_NAME: ${OPEN_GRAPH_BUCKET_NAME}
    ports:
      - 3000:3000
    depends_on:
      - rds-db
    command: ['yarn', 'start']
  rds-db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: syrfbackend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - rds-db:/var/lib/rds
volumes:
  rds-db:
