version: '3.4'

services:
  rawdataserver:
    image: rawdataserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3030
      AWS_S3_ACCESS_KEY_ID:
      AWS_S3_SECRET_ACCESS_KEY:
      AWS_S3_BUCKET:
      DB_HOST: test_db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test_db
    ports:
      - 3030:3030
    volumes:
      - .:/usr/src/app
    links:
      - test_db
  test_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
