var parquet = require('parquetjs-lite');

const estelaPosition = new parquet.ParquetSchema({
  id: { type: 'UTF8' },
  race: { type: 'UTF8' },
  race_original_id: { type: 'UTF8' },
  dorsal: { type: 'UTF8' },
  dorsal_original_id: { type: 'UTF8', optional: true },
  lon: { type: 'UTF8' },
  lat: { type: 'UTF8' },
  timestamp: { type: 'UTF8' },
  s: { type: 'UTF8', optional: true },
  c: { type: 'UTF8', optional: true },
  p: { type: 'UTF8', optional: true },
  w: { type: 'UTF8', optional: true },
  y: { type: 'UTF8', optional: true },
});

const estelaCombined = new parquet.ParquetSchema({
  race_id: { type: 'UTF8' },
  race_original_id: { type: 'UTF8' },
  initLon: { type: 'UTF8', optional: true },
  initLat: { type: 'UTF8', optional: true },
  end: { type: 'UTF8', optional: true },
  end_timestamp: { type: 'UTF8', optional: true },
  ended_at: { type: 'UTF8', optional: true },
  has_ended: { type: 'UTF8', optional: true },
  has_started: { type: 'UTF8', optional: true },
  length: { type: 'UTF8', optional: true },
  name: { type: 'UTF8', optional: true },
  offset: { type: 'UTF8', optional: true },
  onset: { type: 'UTF8', optional: true },
  onset_timestamp: { type: 'UTF8', optional: true },
  scheduled_timestamp: { type: 'UTF8', optional: true },
  start: { type: 'UTF8', optional: true },
  start_timestamp: { type: 'UTF8', optional: true },
  url: { type: 'UTF8', optional: true },
  gpx: { type: 'UTF8', optional: true },
  winds_csv: { type: 'UTF8', optional: true },
  leg_winds_csv: { type: 'UTF8', optional: true },
  results_csv: { type: 'UTF8', optional: true },
  club: { type: 'UTF8', optional: true },
  club_original_id: { type: 'UTF8', optional: true },
  club_data: {
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      user_id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
      lon: { type: 'UTF8', optional: true },
      lat: { type: 'UTF8', optional: true },
      timezone: { type: 'UTF8', optional: true },
      website: { type: 'UTF8', optional: true },
      address: { type: 'UTF8', optional: true },
      twitter: { type: 'UTF8', optional: true },
      api_token: { type: 'UTF8', optional: true },
      phone: { type: 'UTF8', optional: true },
      email: { type: 'UTF8', optional: true },
    },
    optional: true,
  },
  buoys: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      anchored_at: { type: 'UTF8', optional: true },
      door: { type: 'BOOLEAN', optional: true },
      index: { type: 'UTF8', optional: true },
      label: { type: 'UTF8', optional: true },
      lon: { type: 'UTF8', optional: true },
      lat: { type: 'UTF8', optional: true },
      name: { type: 'UTF8', optional: true },
      score: { type: 'BOOLEAN', optional: true },
      updated_at: { type: 'UTF8', optional: true },
      waypoint: { type: 'BOOLEAN', optional: true },
      next_scoring_buoy: { type: 'UTF8', optional: true },
      layline_angle: { type: 'UTF8', optional: true },
      layline_distance: { type: 'UTF8', optional: true },
      radius: { type: 'UTF8', optional: true },
    },
  },
  dorsals: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
      model: { type: 'UTF8', optional: true },
      committee: { type: 'UTF8', optional: true },
      number: { type: 'UTF8', optional: true },
      mmsi: { type: 'UTF8', optional: true },
      pivot_club_id: { type: 'UTF8', optional: true },
      pivot_club_original_id: { type: 'UTF8', optional: true },
      class: { type: 'UTF8', optional: true },
      active: { type: 'UTF8', optional: true },
      track_csv: { type: 'UTF8', optional: true },
    },
  },
  players: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      dorsal: { type: 'UTF8', optional: true },
      dorsal_original_id: { type: 'UTF8', optional: true },
      class: { type: 'UTF8', optional: true },
      name: { type: 'UTF8', optional: true },
      number: { type: 'UTF8', optional: true },
      committee: { type: 'UTF8', optional: true },
    },
  },
  positions: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      dorsal: { type: 'UTF8' },
      dorsal_original_id: { type: 'UTF8', optional: true },
      lon: { type: 'UTF8' },
      lat: { type: 'UTF8' },
      timestamp: { type: 'UTF8' },
      s: { type: 'UTF8', optional: true },
      c: { type: 'UTF8', optional: true },
      p: { type: 'UTF8', optional: true },
      w: { type: 'UTF8', optional: true },
      y: { type: 'UTF8', optional: true },
    },
  },
  results: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      dorsal: { type: 'UTF8', optional: true },
      dorsal_original_id: { type: 'UTF8', optional: true },
      laraval_through_key: { type: 'UTF8', optional: true },
      timestamp: { type: 'UTF8', optional: true },
    },
  },
});

module.exports = {
  estelaPosition,
  estelaCombined,
};
