var parquet = require('parquetjs-lite');

const raceQsCombined = new parquet.ParquetSchema({
  event_id: { type: 'UTF8' },
  event_original_id: { type: 'UTF8' },
  regatta: { type: 'UTF8' },
  regatta_original_id: { type: 'UTF8' },
  regatta_data: {
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      club_original_id: { type: 'UTF8', optional: true },
      name: { type: 'UTF8', optional: true },
      url: { type: 'UTF8', optional: true },
      content: { type: 'UTF8', optional: true },
      attach1: { type: 'UTF8', optional: true },
      attach2: { type: 'UTF8', optional: true },
      attach3: { type: 'UTF8', optional: true },
      attach4: { type: 'UTF8', optional: true },
      type: { type: 'UTF8', optional: true },
      administrator: { type: 'UTF8', optional: true },
      updated_at: { type: 'UTF8', optional: true },
      contactor_name: { type: 'UTF8', optional: true },
      contactor_email: { type: 'UTF8', optional: true },
    },
  },
  name: { type: 'UTF8', optional: true },
  content: { type: 'UTF8', optional: true },
  from: { type: 'UTF8', optional: true },
  till: { type: 'UTF8', optional: true },
  tz: { type: 'UTF8', optional: true },
  lat1: { type: 'UTF8', optional: true },
  lon1: { type: 'UTF8', optional: true },
  lat2: { type: 'UTF8', optional: true },
  lon2: { type: 'UTF8', optional: true },
  updated_at: { type: 'UTF8', optional: true },
  url: { type: 'UTF8', optional: true },
  divisions: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      regatta: { type: 'UTF8' },
      regatta_original_id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
      avatar: { type: 'UTF8', optional: true },
    },
  },
  participants: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      boat: { type: 'UTF8' },
      start: { type: 'UTF8' },
      finish: { type: 'UTF8' },
    },
  },
  positions: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      participant: { type: 'UTF8' },
      participant_original_id: { type: 'UTF8' },
      time: { type: 'UTF8', optional: true },
      lat: { type: 'UTF8', optional: true },
      lon: { type: 'UTF8', optional: true },
      roll: { type: 'UTF8', optional: true },
      pitch: { type: 'UTF8', optional: true },
      heading: { type: 'UTF8', optional: true },
      sow: { type: 'UTF8', optional: true },
      wind_angle: { type: 'UTF8', optional: true },
      wind_speed: { type: 'UTF8', optional: true },
    },
  },
  routes: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      start: { type: 'UTF8' },
      start_original_id: { type: 'UTF8' },
      waypoint: { type: 'UTF8' },
      waypoint_original_id: { type: 'UTF8' },
      sqk: { type: 'UTF8', optional: true },
      wind_direction: { type: 'UTF8', optional: true },
      wind_speed: { type: 'UTF8', optional: true },
      current_direction: { type: 'UTF8', optional: true },
      current_speed: { type: 'UTF8', optional: true },
    },
  },
  starts: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      division: { type: 'UTF8' },
      division_original_id: { type: 'UTF8' },
      from: { type: 'UTF8', optional: true },
      type: { type: 'UTF8', optional: true },
      wind: { type: 'UTF8', optional: true },
      min_duration: { type: 'UTF8', optional: true },
    },
  },
  waypoints: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      regatta: { type: 'UTF8' },
      regatta_original_id: { type: 'UTF8' },
      start: { type: 'UTF8', optional: true },
      finish: { type: 'UTF8', optional: true },
      lat: { type: 'UTF8', optional: true },
      lon: { type: 'UTF8', optional: true },
      lat2: { type: 'UTF8', optional: true },
      lon2: { type: 'UTF8', optional: true },
      port_course: { type: 'UTF8', optional: true },
      port_speed: { type: 'UTF8', optional: true },
      starboard_course: { type: 'UTF8', optional: true },
      starboard_speed: { type: 'UTF8', optional: true },
      wind: { type: 'UTF8', optional: true },
      tack: { type: 'UTF8', optional: true },
      type: { type: 'UTF8', optional: true },
      v: { type: 'UTF8', optional: true },
      start_I: { type: 'UTF8', optional: true },
      finish_I: { type: 'UTF8', optional: true },
      start_Z: { type: 'UTF8', optional: true },
      finish_Z: { type: 'UTF8', optional: true },
      name: { type: 'UTF8', optional: true },
      race_type: { type: 'UTF8', optional: true },
      boat_model: { type: 'UTF8', optional: true },
    },
  },
});

module.exports = {
  raceQsCombined,
};
