const parquet = require('parquetjs-lite');

const regadataRaceCombined = new parquet.ParquetSchema({
  id: { type: 'UTF8' },
  original_id: { type: 'UTF8' },
  sails: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8', optional: true },
      race_id: { type: 'UTF8' },
      race_original_id: { type: 'UTF8', optional: true },
      sail: { type: 'UTF8', optional: true },
      skipper: { type: 'UTF8', optional: true },
      boat: { type: 'UTF8', optional: true },
      color: { type: 'UTF8', optional: true },
      class: { type: 'UTF8', optional: true },
      twitter: { type: 'UTF8', optional: true },
      twitter2: { type: 'UTF8', optional: true },
      twitter_skipper1: { type: 'UTF8', optional: true },
      twitter_skipper2: { type: 'UTF8', optional: true },
      twitter_sponsor: { type: 'UTF8', optional: true },
      url_skipper1: { type: 'UTF8', optional: true },
      url_skipper2: { type: 'UTF8', optional: true },
      url_sponsor: { type: 'UTF8', optional: true },
      fb_skipper1: { type: 'UTF8', optional: true },
      fb_skipper2: { type: 'UTF8', optional: true },
      fb_sponsor: { type: 'UTF8', optional: true },
      youtube_skipper1: { type: 'UTF8', optional: true },
      youtube_skipper2: { type: 'UTF8', optional: true },
      youtube_sponsor: { type: 'UTF8', optional: true },
    },
  },
});

const regadataReport = new parquet.ParquetSchema({
  id: { type: 'UTF8' },
  original_object_id: { type: 'UTF8', optional: true },
  original_id: { type: 'UTF8', optional: true },
  race_id: { type: 'UTF8', optional: true },
  race_original_id: { type: 'UTF8', optional: true },
  rank: { type: 'INT32', optional: true },
  country: { type: 'UTF8', optional: true },
  sail_id: { type: 'UTF8', optional: true },
  sail: { type: 'UTF8', optional: true },
  skipper: { type: 'UTF8', optional: true },
  boat: { type: 'UTF8', optional: true },
  source: { type: 'UTF8', optional: true },
  class: { type: 'UTF8', optional: true },
  time: { type: 'UTF8', optional: true },
  date: { type: 'UTF8', optional: true },
  timestamp: { type: 'INT64', optional: true },
  lat_dms: { type: 'UTF8', optional: true },
  lon_dms: { type: 'UTF8', optional: true },
  lat_dec: { type: 'DOUBLE', optional: true },
  lon_dec: { type: 'DOUBLE', optional: true },
  '1hour_heading': { type: 'DOUBLE', optional: true },
  '1hour_speed': { type: 'DOUBLE', optional: true },
  '1hour_vmg': { type: 'DOUBLE', optional: true },
  '1hour_distance': { type: 'DOUBLE', optional: true },
  lastreport_heading: { type: 'INT64', optional: true },
  lastreport_vmg: { type: 'DOUBLE', optional: true },
  lastreport_distance: { type: 'DOUBLE', optional: true },
  '24hour_heading': { type: 'DOUBLE', optional: true },
  '24hour_speed': { type: 'DOUBLE', optional: true },
  '24hour_vmg': { type: 'DOUBLE', optional: true },
  '24hour_distance': { type: 'DOUBLE', optional: true },
  dtf: { type: 'DOUBLE', optional: true },
  dtl: { type: 'DOUBLE', optional: true },
  total_distance: { type: 'DOUBLE', optional: true },
  dtl_diff: { type: 'DOUBLE', optional: true },
  color: { type: 'UTF8', optional: true },
});

module.exports = {
  regadataRaceCombined,
  regadataReport,
};
