var parquet = require('parquetjs-lite');

const tractracCombined = new parquet.ParquetSchema({
  race_id: { type: 'UTF8' },
  original_race_id: { type: 'UTF8' },
  event: { type: 'UTF8', optional: true },
  event_original_id: { type: 'UTF8', optional: true },
  event_data: {
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      name: { type: 'UTF8' },
      external_website: { type: 'UTF8', optional: true },
      country: { type: 'UTF8', optional: true },
      city: { type: 'UTF8', optional: true },
      start: { type: 'UTF8', optional: true },
      end: { type: 'UTF8', optional: true },
      type: { type: 'UTF8', optional: true },
      web_url: { type: 'UTF8', optional: true },
      sap_url: { type: 'UTF8', optional: true },
      sap_event_url: { type: 'UTF8', optional: true },
      sap_leaderboard_name: { type: 'UTF8', optional: true },
      lat: { type: 'UTF8', optional: true },
      lon: { type: 'UTF8', optional: true },
    },
    optional: true,
  },
  name: { type: 'UTF8' },
  url: { type: 'UTF8' },
  tracking_start: { type: 'UTF8', optional: true },
  tracking_stop: { type: 'UTF8', optional: true },
  race_start: { type: 'UTF8', optional: true },
  race_end: { type: 'UTF8', optional: true },
  status: { type: 'UTF8', optional: true },
  lon: { type: 'UTF8', optional: true },
  lat: { type: 'UTF8', optional: true },
  calculated_start_time: { type: 'UTF8', optional: true },
  race_handicap: { type: 'UTF8', optional: true },
  classes: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      boat_class: { type: 'UTF8' },
      original_boat_class_id: { type: 'UTF8' },
      name: { type: 'UTF8' },
    },
  },
  routes: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
    },
  },
  competitors: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      class: { type: 'UTF8' },
      class_original_id: { type: 'UTF8' },
      classrace_id: { type: 'UTF8' },
      class_name: { type: 'UTF8', optional: true },
      description: { type: 'UTF8', optional: true },
      handicap: { type: 'UTF8', optional: true },
      handicap_distance: { type: 'UTF8', optional: true },
      start_time: { type: 'UTF8', optional: true },
      finish_time: { type: 'UTF8', optional: true },
      stop_time: { type: 'UTF8', optional: true },
      status_original_id: { type: 'UTF8', optional: true },
      status_full: { type: 'UTF8', optional: true },
      status_time: { type: 'UTF8', optional: true },
      first_name: { type: 'UTF8', optional: true },
      last_name: { type: 'UTF8', optional: true },
      name: { type: 'UTF8', optional: true },
      short_name: { type: 'UTF8', optional: true },
      name_alias: { type: 'UTF8', optional: true },
      short_alias: { type: 'UTF8', optional: true },
      nationality: { type: 'UTF8', optional: true },
      non_competing: { type: 'UTF8', optional: true },
      handicap_tod: { type: 'UTF8', optional: true },
      handicap_tot: { type: 'UTF8', optional: true },
    },
  },
  competitorResults: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      competitor: { type: 'UTF8' },
      competitor_original_id: { type: 'UTF8' },
      time_elapsed: { type: 'UTF8', optional: true },
      start_time: { type: 'UTF8', optional: true },
      stop_time: { type: 'UTF8', optional: true },
      finish_time: { type: 'UTF8', optional: true },
      status: { type: 'UTF8', optional: true },
      team_name: { type: 'UTF8', optional: true },
      team_original_id: { type: 'UTF8', optional: true },
    },
  },
  competitorPassings: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      competitor: { type: 'UTF8' },
      competitor_original_id: { type: 'UTF8' },
      control: { type: 'UTF8', optional: true },
      control_original_id: { type: 'UTF8', optional: true },
      passing_time: { type: 'UTF8', optional: true },
      real_passing_time: { type: 'UTF8', optional: true },
      pos: { type: 'UTF8', optional: true },
      time_from_start: { type: 'UTF8', optional: true },
    },
  },
  competitorPositions: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      competitor: { type: 'UTF8' },
      competitor_original_id: { type: 'UTF8' },
      lat: { type: 'UTF8' },
      lon: { type: 'UTF8' },
      height: { type: 'UTF8', optional: true },
      speed: { type: 'UTF8', optional: true },
      direction: { type: 'UTF8', optional: true },
      m: { type: 'UTF8', optional: true },
      timestamp: { type: 'UTF8', optional: true },
      speed_avg: { type: 'UTF8', optional: true },
    },
  },
  controls: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      original_id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
      route: { type: 'UTF8' },
      route_original_id: { type: 'UTF8' },
    },
  },
  controlPoints: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
      route: { type: 'UTF8' },
      route_original_id: { type: 'UTF8' },
      control: { type: 'UTF8' },
      control_original_id: { type: 'UTF8' },
    },
  },
  controlPointPositions: {
    repeated: true,
    fields: {
      id: { type: 'UTF8' },
      name: { type: 'UTF8', optional: true },
      route: { type: 'UTF8' },
      route_original_id: { type: 'UTF8' },
      controlpoint: { type: 'UTF8' },
      lat: { type: 'UTF8' },
      lon: { type: 'UTF8' },
      height: { type: 'UTF8', optional: true },
      speed: { type: 'UTF8', optional: true },
      direction: { type: 'UTF8', optional: true },
      m: { type: 'UTF8', optional: true },
      timestamp: { type: 'UTF8', optional: true },
      speed_avg: { type: 'UTF8', optional: true },
    },
  },
});

module.exports = {
  tractracCombined,
};
